apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    k8s-app: ddns-route53
  name: ddns-route53
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ddns-route53
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: ddns-route53
      name: ddns-route53
    spec:
      containers:
      - image: quay.io/dcooley/ds-ddns-route53:v1
        imagePullPolicy: Always
        env:
        - name: DDNS_ROUTE53_ZONE_ID
          value: "ZONEID"
        - name: DDNS_ROUTE53_TTL
          value: "300"
        - name: DDNS_ROUTE53_COMMENT
          value: "Created by the ddns-route53 daemonset"
        - name: DDNS_ROUTE53_DOMAIN
          value: "Domain"
        - name: DDNS_ROUTE53_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DDNS_ROUTE53_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        name: ddns-route53
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 50m
            memory: 40Mi
      dnsPolicy: ClusterFirst
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  updateStrategy:
    rollingUpdate:
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
