apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: ddns-route53
  name: ddns-route53
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ddns-route53
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: ddns-route53
      name: ddns-route53
    spec:
      containers:
        image: quay.io/dcooley/ds-ddns-route53:v1
        imagePullPolicy: Always
        args: ["-z", "Z2K2L7AMLT2JPI", "-r", "test.se.k8s.work", "-i", "10.0.0.1"]
        env:
        - name: DDNS_ROUTE53_ZONE_ID
          value: "Z2K2L7AMLT2JPI"
        - name: DDNS_ROUTE53_TTL
          value: "300"
        - name: DDNS_ROUTE53_COMMENT
          value: "Created by the ddns-route53 damemonset"
        - name: DDNS_ROUTE53_RECORD_SET
          value: 
        name: ddns-route53
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
